export enum IFOLDER_NAMES {
    IMAGE = 'image',
    IMAGES = 'images',
    GALLARY = 'gallary',
    LICENSE = 'license',
    DRIVER_LICENSE = 'driverLicense',
    INSURANCE = 'insurance',
    PERMITS = 'permits',
    BANNER = 'banner',
    LOGO = 'logo',
    AUDIO = 'audio',
    VIDEO = 'video',
    DOCUMENT = 'document',
    THUMBNAIL = 'thumbnail',
    OTHERS = 'others',
}